version: "3.8"

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: socket
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    networks:
      - app-network

  # Angular Frontend service
  # ng-app:
  #   build:
  #     context: ./seculearn-frontend/
  #   container_name: ng-app
  #   ports:
  #     - "8000:80"
  #   environment:
  #     API_URL: http://node-app:3000
  #   restart: always
  #   networks:
  #     - app-network
  
  # Node.js Backend service
  node-app:
    build:
      context: ./node/
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./node:/usr/src/app
    command: ["npm", "run", "dev"]

# Define the network for both services to communicate
networks:
  app-network:
    driver: bridge

# Define volumes for persistent data
volumes:
  mongo-data:
    driver: local
